name: Deploy to Hugging Face Spaces 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.12

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Check for Changes
        id: git-check
        run: |
          git fetch origin main
          git status --porcelain | tee changes.log
          if [ -s changes.log ]; then
            echo "Changes detected. Proceeding with deployment."
            echo "::set-output name=deploy::true"
          else
            echo "No changes detected. Skipping deployment."
            echo "::set-output name=deploy::false"
          fi
      - name: Pull latest changes before pushing
        run: |
            git pull --rebase origin main || echo "Nothing to pull"
            git push origin main || echo "No new changes to push"
        

      - name: Upload to Hugging Face Spaces
        if: steps.git-check.outputs.deploy == 'true'
        env:
          HF_USERNAME: ${{ secrets.HF_USERNAME }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "vemuboddupalli@gmail.com"
          git config --global user.name "lohithkumar12"
          git remote set-url origin "https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/lohithkumar01/spotify-song-recommendation.git"
          git add .
          git commit -m "Auto-deploy from GitHub Actions" || echo "No new changes to commit"
          git push origin main || echo "No new changes to push"
